# start from steelscript base
FROM riverbed/steelscript:slim
MAINTAINER Riverbed Technology

RUN set -ex \
        && buildDeps=' \
                gcc \
                g++ \
                Cython \
                libssl-dev \
                libpq-dev \
        ' \
        && install=' \
                libmagic-dev \ 
        ' \
        && apt-get update && apt-get install -y $buildDeps $install --no-install-recommends && rm -rf /var/lib/apt/lists/* \
        \
        && pip install psycopg2 gunicorn \
        && pip install --src /src -e git+https://github.com/riverbed/steelscript-appfwk#egg=steelscript-appfwk \
        && pip install --src /src \
            -e git+https://github.com/riverbed/steelscript-appfwk-business-hours#egg=steelscript-appfwk-business_hours \
            -e git+https://github.com/riverbed/steelscript-stock#egg=steelscript-stock \
        && rm -f /src/pip-delete-this-directory.txt \
        && apt-get purge -y --auto-remove $buildDeps \
        && rm -rf ~/.cache

